treat detached HEAD commits

diff --git a/.github/workflows/publish_release.yml b/.github/workflows/publish_release.yml
--- a/.github/workflows/publish_release.yml
+++ b/.github/workflows/publish_release.yml
@@ -69,16 +69,16 @@ jobs:
           find_commit_res=`scripts/find_version_commit.pl "${{ steps.package_version.outputs.version_commit }}"`
           echo -e "$find_commit_res"
           find_commit_res=`echo "$find_commit_res" | grep -i " by "`
-          if [ -z "$find_commit_res" ]; then echo "could not find GIT VERSION COMMIT"; exit 1; fi;
+#          if [ -z "$find_commit_res" ]; then echo "could not find GIT VERSION COMMIT"; exit 1; fi;
           merge_commit=`echo "$find_commit_res" | cut -d' ' -f1 | cut -d'/' -f2`
           merge_user=`echo "$find_commit_res" | cut -d"'" -f2 | cut -d'/' -f1`
           merge_email=`echo "$find_commit_res" | cut -d"'" -f2 | cut -d'/' -f2`
           git config user.name "$merge_user"
           git config user.email "$merge_email"
           git tag -a "${{ steps.package_version.outputs.version }}" $merge_commit -m "${{ steps.package_version.outputs.package }} ${{ steps.package_version.outputs.version }} released"
-          git push origin ${{ steps.package_version.outputs.version }}
-          git fetch --tags
-          git checkout ${{ steps.cargo_version.outputs.version }}
+#          git push origin ${{ steps.package_version.outputs.version }}
+#          git fetch --tags
+#          git checkout ${{ steps.package_version.outputs.version }}
           
       - name: Build Release Version
         id: build_release
