install cpan-uploader

diff --git a/.github/workflows/publish_release.yml b/.github/workflows/publish_release.yml
--- a/.github/workflows/publish_release.yml
+++ b/.github/workflows/publish_release.yml
@@ -30,7 +30,8 @@ jobs:
       - name: Install Perl Dependencies
         run: | 
           perl --version
-          sudo apt-get update && sudo apt-get -y install git libpath-tiny-perl libcpanel-json-xs-perl libjson-xs-perl libjson-perl libdata-dump-perl        
+          sudo apt-get update && sudo apt-get -y install git libpath-tiny-perl libcpanel-json-xs-perl libjson-xs-perl libjson-perl libdata-dump-perl libcpan-uploader-perl
+        
       
       - name: Checkout
         uses: actions/checkout@v2
@@ -106,17 +107,19 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.PROJECT_RELEASE_TOKEN }}       
                       
 #          if [ $duplicated -ne 1 ]; then exit $publish_res ; fi;
+
+#          cpan-upload -v 2>cpan-upload_error.log > cpan-upload.log ; echo "Exit Code: '$?'" >> cpan-upload.log || true
+#          publish_res=$?
+#          duplicated=`cat cpan-upload_error.log | grep -i "already uploaded" | wc -l`
+#          echo "CPAN Upload Report:"
+#          cat cpan-upload.log
+#          echo "CPAN Upload Error:"
+#          cat cpan-upload_error.log
       - name: CPAN Publish
         id: publish
         if: steps.git_tag.outputs.exists == 0
         run: |
           echo "${{ secrets.PAUSE_LOGIN }}" > ~/.pause
-          cpan-upload -v 2>cpan-upload_error.log > cpan-upload.log ; echo "Exit Code: '$?'" >> cpan-upload.log || true
-          publish_res=$?
-          duplicated=`cat cpan-upload_error.log | grep -i "already uploaded" | wc -l`
-          echo "CPAN Upload Report:"
-          cat cpan-upload.log
-          echo "CPAN Upload Error:"
-          cat cpan-upload_error.log
+          cpan-upload -v 
           
         
