reenable complete release workflow

diff --git a/.github/workflows/publish_release.yml b/.github/workflows/publish_release.yml
--- a/.github/workflows/publish_release.yml
+++ b/.github/workflows/publish_release.yml
@@ -60,17 +60,6 @@ jobs:
           echo "tag=$tag_label" >> $GITHUB_OUTPUT
           echo "exists=$tag_exists" >> $GITHUB_OUTPUT
         
-#          if [ -z "$find_commit_res" ]; then echo "could not find GIT VERSION COMMIT"; exit 1; fi;
-#          git push origin ${{ steps.package_version.outputs.version }}
-#          git fetch --tags
-#          git checkout ${{ steps.package_version.outputs.version }}
-#          find_commit_res=`echo "$find_commit_res" | grep -i " by "`
-#          merge_commit=`echo "$find_commit_res" | cut -d' ' -f1 | cut -d'/' -f2`
-#          merge_user=`echo "$find_commit_res" | cut -d"'" -f2 | cut -d'/' -f1`
-#          merge_email=`echo "$find_commit_res" | cut -d"'" -f2 | cut -d'/' -f2`
-#          git config user.name "$merge_user"
-#          git config user.email "$merge_email"
-#          git tag -a "${{ steps.package_version.outputs.version }}" $merge_commit -m "${{ steps.package_version.outputs.package }} ${{ steps.package_version.outputs.version }} released"
       - name: Tag the Repository with Package Version Tag
         id: git_tag_set
         if: steps.git_tag.outputs.exists == 0
@@ -79,6 +68,17 @@ jobs:
           echo "git - commit: '${{ steps.package_version.outputs.version_commit }}'"
           find_commit_res=`scripts/find_version_commit.pl "${{ steps.package_version.outputs.version_commit }}"` || true
           echo -e "$find_commit_res"
+          find_commit_res=`echo "$find_commit_res" | grep -i " by "`
+          if [ -z "$find_commit_res" ]; then echo "could not find GIT VERSION COMMIT"; exit 1; fi;
+          merge_commit=`echo "$find_commit_res" | cut -d' ' -f1 | cut -d'/' -f2`
+          merge_user=`echo "$find_commit_res" | cut -d"'" -f2 | cut -d'/' -f1`
+          merge_email=`echo "$find_commit_res" | cut -d"'" -f2 | cut -d'/' -f2`
+          git config user.name "$merge_user"
+          git config user.email "$merge_email"
+          git tag -a "${{ steps.package_version.outputs.version }}" $merge_commit -m "${{ steps.package_version.outputs.package }} ${{ steps.package_version.outputs.version }} released"
+          git push origin ${{ steps.package_version.outputs.version }}
+          git fetch --tags
+          git checkout ${{ steps.package_version.outputs.version }}
           
       - name: Build Release Version
         id: build_release
